CREATE SEQUENCE IF NOT EXISTS campaign_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS campaign_location_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS character_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS character_log_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS combatant_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS encounter_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS faction_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS key_item_tracker_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS player_log_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS prep_item_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS quest_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS session_agenda_item_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS session_decision_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS session_encounter_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS session_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS session_key_item_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS session_note_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS tag_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE campaign
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    last_session_date  TIMESTAMP WITHOUT TIME ZONE,
    pinned             BOOLEAN DEFAULT FALSE                   NOT NULL,
    thumbnail_url      VARCHAR(255),
    title              VARCHAR(255),
    description        VARCHAR(10000),
    archived           BOOLEAN DEFAULT FALSE                   NOT NULL,
    adventure_code     VARCHAR(255),
    max_level          INTEGER,
    min_level          INTEGER,
    status             VARCHAR(255),
    visible_to_players BOOLEAN DEFAULT FALSE                   NOT NULL,
    version            BIGINT  DEFAULT 0,
    dm_notes_private   TEXT,
    dm_notes_public    TEXT,
    banner_image_url   VARCHAR(255),
    CONSTRAINT campaign_pkey PRIMARY KEY (id)
);

CREATE TABLE campaign_factions
(
    campaign_id BIGINT NOT NULL,
    faction_id  BIGINT NOT NULL,
    CONSTRAINT campaign_factions_pkey PRIMARY KEY (campaign_id, faction_id)
);

CREATE TABLE campaign_location
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    campaign_id BIGINT,
    CONSTRAINT campaign_location_pkey PRIMARY KEY (id)
);

CREATE TABLE campaign_sections
(
    campaign_id BIGINT NOT NULL,
    title       VARCHAR(255)
);

CREATE TABLE campaign_tags
(
    campaign_id BIGINT NOT NULL,
    tag_id      BIGINT NOT NULL
);

CREATE TABLE character
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    armor_class           INTEGER                                 NOT NULL,
    character_name        VARCHAR(255),
    charisma              INTEGER                                 NOT NULL,
    class_and_level       VARCHAR(255),
    constitution          INTEGER                                 NOT NULL,
    dexterity             INTEGER                                 NOT NULL,
    experience            INTEGER                                 NOT NULL,
    hit_points            INTEGER                                 NOT NULL,
    initiative            INTEGER                                 NOT NULL,
    intelligence          INTEGER                                 NOT NULL,
    jack_of_all_trades    BOOLEAN                                 NOT NULL,
    level                 INTEGER                                 NOT NULL,
    level_override        BOOLEAN                                 NOT NULL,
    notes                 TEXT,
    passive_insight       BOOLEAN                                 NOT NULL,
    passive_investigation BOOLEAN                                 NOT NULL,
    passive_perception    BOOLEAN                                 NOT NULL,
    player_controlled     VARCHAR(255)                            NOT NULL,
    player_name           VARCHAR(255),
    speed                 INTEGER                                 NOT NULL,
    spelldc               INTEGER                                 NOT NULL,
    strength              INTEGER                                 NOT NULL,
    wisdom                INTEGER                                 NOT NULL,
    campaign_id           BIGINT,
    created_at            TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    updated_at            TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    avatar                VARCHAR(255),
    character_class       VARCHAR(255),
    gp                    INTEGER DEFAULT 0                       NOT NULL,
    sp                    INTEGER DEFAULT 0                       NOT NULL,
    cp                    INTEGER DEFAULT 0                       NOT NULL,
    CONSTRAINT character_pkey PRIMARY KEY (id)
);

CREATE TABLE character_log
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    character_name     VARCHAR(255)                            NOT NULL,
    class_and_level    VARCHAR(255)                            NOT NULL,
    custom_notes       TEXT,
    death_saves_failed INTEGER                                 NOT NULL,
    downtime_gained    INTEGER                                 NOT NULL,
    faction            VARCHAR(255),
    gold_earned        numeric(38, 2)                          NOT NULL,
    inspiration_used   BOOLEAN                                 NOT NULL,
    player_name        VARCHAR(255)                            NOT NULL,
    campaign_id        BIGINT,
    session_id         BIGINT                                  NOT NULL,
    CONSTRAINT character_log_pkey PRIMARY KEY (id)
);

CREATE TABLE character_log_magic_items
(
    character_log_id BIGINT       NOT NULL,
    magic_item       VARCHAR(255) NOT NULL,
    CONSTRAINT player_log_magic_items_pkey PRIMARY KEY (character_log_id, magic_item)
);

CREATE TABLE combatant
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    hp           INTEGER                                 NOT NULL,
    xp           INTEGER                                 NOT NULL,
    cr           DOUBLE PRECISION                        NOT NULL,
    initiative   INTEGER,
    is_template  BOOLEAN DEFAULT FALSE                   NOT NULL,
    encounter_id BIGINT,
    ac           INTEGER                                 NOT NULL,
    legendary    BOOLEAN                                 NOT NULL,
    quantity     INTEGER                                 NOT NULL,
    CONSTRAINT combatant_pkey PRIMARY KEY (id)
);

CREATE TABLE combatant_actions
(
    combatant_id BIGINT       NOT NULL,
    action       VARCHAR(255) NOT NULL,
    CONSTRAINT pk_combatant_actions PRIMARY KEY (combatant_id, action)
);

CREATE TABLE combatant_special_abilities
(
    combatant_id    BIGINT       NOT NULL,
    special_ability VARCHAR(255) NOT NULL,
    CONSTRAINT pk_combatant_special_abilities PRIMARY KEY (combatant_id, special_ability)
);

CREATE TABLE encounter
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR(255)                            NOT NULL,
    notes            TEXT,
    session_id       BIGINT                                  NOT NULL,
    total_xp         INTEGER          DEFAULT 0              NOT NULL,
    challenge_rating DOUBLE PRECISION DEFAULT 0              NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    updated_at       TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    CONSTRAINT encounter_pkey PRIMARY KEY (id)
);

CREATE TABLE faction
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT faction_pkey PRIMARY KEY (id)
);

CREATE TABLE key_item_tracker
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    session_id     BIGINT                                  NOT NULL,
    item_name      VARCHAR(255),
    description    TEXT,
    acquired       BOOLEAN DEFAULT FALSE,
    location_found VARCHAR(255),
    used_in        TEXT,
    CONSTRAINT key_item_tracker_pkey PRIMARY KEY (id)
);

CREATE TABLE player_character_condition_immunities
(
    player_character_id  BIGINT NOT NULL,
    condition_immunities VARCHAR(255)
);

CREATE TABLE player_character_damage_immunities
(
    player_character_id BIGINT NOT NULL,
    damage_immunities   VARCHAR(255)
);

CREATE TABLE player_character_damage_resistances
(
    player_character_id BIGINT NOT NULL,
    damage_resistances  VARCHAR(255)
);

CREATE TABLE player_character_damage_vulnerabilities
(
    player_character_id    BIGINT NOT NULL,
    damage_vulnerabilities VARCHAR(255)
);

CREATE TABLE player_character_inventory
(
    character_id BIGINT NOT NULL,
    item_index   VARCHAR(255)
);

CREATE TABLE player_character_skill_proficiencies
(
    player_character_id BIGINT NOT NULL,
    skill_proficiencies VARCHAR(255)
);

CREATE TABLE player_log
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message            VARCHAR(255),
    timestamp          TIMESTAMP WITHOUT TIME ZONE,
    campaign_id        BIGINT,
    session_id         BIGINT                                  NOT NULL,
    player_name        VARCHAR(255)                            NOT NULL,
    character_name     VARCHAR(255)                            NOT NULL,
    class_and_level    VARCHAR(255)                            NOT NULL,
    faction            VARCHAR(255),
    inspiration_used   BOOLEAN        DEFAULT FALSE            NOT NULL,
    death_saves_failed INTEGER        DEFAULT 0                NOT NULL,
    gold_earned        numeric(38, 2) DEFAULT 0                NOT NULL,
    downtime_gained    INTEGER        DEFAULT 0                NOT NULL,
    renown             INTEGER        DEFAULT 0                NOT NULL,
    custom_notes       TEXT,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    is_critical        BOOLEAN        DEFAULT FALSE            NOT NULL,
    file_url           VARCHAR(255),
    CONSTRAINT player_log_pkey PRIMARY KEY (id)
);

CREATE TABLE player_log_magic_items
(
    player_log_id BIGINT NOT NULL,
    magic_item    VARCHAR(255)
);

CREATE TABLE prep_item
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    done               BOOLEAN                                 NOT NULL,
    title              VARCHAR(255)                            NOT NULL,
    type               VARCHAR(255),
    campaign_id        BIGINT                                  NOT NULL,
    description        TEXT,
    status             VARCHAR(255)                            NOT NULL,
    visible_to_players BOOLEAN                                 NOT NULL,
    session_id         BIGINT,
    created_at         TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    updated_at         TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    file_url           VARCHAR(255),
    is_critical        BOOLEAN                                 NOT NULL,
    CONSTRAINT prep_item_pkey PRIMARY KEY (id)
);

CREATE TABLE quest
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title              VARCHAR(255)                            NOT NULL,
    description        TEXT,
    status             VARCHAR(255)                            NOT NULL,
    priority           VARCHAR(255)                            NOT NULL,
    visible_to_players BOOLEAN                                 NOT NULL,
    linked_session_id  BIGINT,
    campaign_id        BIGINT                                  NOT NULL,
    completed_at       TIMESTAMP WITHOUT TIME ZONE,
    created_at         TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    updated_at         TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    notes              VARCHAR(255),
    quest_giver        VARCHAR(255),
    reward             VARCHAR(255),
    CONSTRAINT quest_pkey PRIMARY KEY (id)
);

CREATE TABLE quest_tags
(
    quest_id BIGINT       NOT NULL,
    tag      VARCHAR(255) NOT NULL,
    CONSTRAINT quest_tags_pkey PRIMARY KEY (quest_id, tag)
);

CREATE TABLE session
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    session_date        TIMESTAMP WITHOUT TIME ZONE,
    campaign_id         BIGINT,
    created_at          TIMESTAMP WITHOUT TIME ZONE,
    objective           VARCHAR(1000),
    status              VARCHAR(255)                            NOT NULL,
    summary             VARCHAR(4000),
    title               VARCHAR(255)                            NOT NULL,
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    character_id        BIGINT,
    player_character_id BIGINT,
    attendance_notes    TEXT,
    past_notes          TEXT,
    upcoming_notes      TEXT,
    CONSTRAINT session_pkey PRIMARY KEY (id)
);

CREATE TABLE session_agenda_item
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content    VARCHAR(1000)                           NOT NULL,
    dm_only    BOOLEAN                                 NOT NULL,
    sort_order INTEGER,
    session_id BIGINT                                  NOT NULL,
    sort_oder  INTEGER,
    CONSTRAINT session_agenda_item_pkey PRIMARY KEY (id)
);

CREATE TABLE session_decision
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    choice_made    VARCHAR(1000)                           NOT NULL,
    consequences   VARCHAR(1000),
    decision_point VARCHAR(1000)                           NOT NULL,
    session_id     BIGINT                                  NOT NULL,
    CONSTRAINT session_decision_pkey PRIMARY KEY (id)
);

CREATE TABLE session_encounter
(
    id                   BIGINT       NOT NULL,
    estimated_difficulty VARCHAR(255),
    location             VARCHAR(255),
    name                 VARCHAR(255) NOT NULL,
    outcome              VARCHAR(1000),
    player_visible       BOOLEAN      NOT NULL,
    session_id           BIGINT       NOT NULL,
    CONSTRAINT session_encounter_pkey PRIMARY KEY (id)
);

CREATE TABLE session_key_item
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    acquired       BOOLEAN                                 NOT NULL,
    description    VARCHAR(1000),
    item_name      VARCHAR(255)                            NOT NULL,
    location_found VARCHAR(255),
    used_in        VARCHAR(255),
    session_id     BIGINT                                  NOT NULL,
    CONSTRAINT session_key_item_pkey PRIMARY KEY (id)
);

CREATE TABLE session_note
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content    VARCHAR(1500),
    type       VARCHAR(255)                            NOT NULL,
    session_id BIGINT                                  NOT NULL,
    CONSTRAINT session_note_pkey PRIMARY KEY (id)
);

CREATE TABLE tag
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT tag_pkey PRIMARY KEY (id)
);

ALTER TABLE tag
    ADD CONSTRAINT uk1wdpsed5kna2y38hnbgrnhi5b UNIQUE (name);

ALTER TABLE faction
    ADD CONSTRAINT ukon773aedpwov7txb4o1rco372 UNIQUE (name);

ALTER TABLE player_log
    ADD CONSTRAINT fk1hhb4ercbetbu9hnao19jv2av FOREIGN KEY (session_id) REFERENCES session (id) ON DELETE NO ACTION;

ALTER TABLE campaign_location
    ADD CONSTRAINT fk25n968ted1yaybnk7376gbmda FOREIGN KEY (campaign_id) REFERENCES campaign (id) ON DELETE NO ACTION;

ALTER TABLE player_character_condition_immunities
    ADD CONSTRAINT fk3yjxml6xxsdt8el1b9d4fuun1 FOREIGN KEY (player_character_id) REFERENCES character (id) ON DELETE NO ACTION;

ALTER TABLE campaign_factions
    ADD CONSTRAINT fk4tmvv8s5nirs2k88fwqw1xcfk FOREIGN KEY (campaign_id) REFERENCES campaign (id) ON DELETE NO ACTION;

ALTER TABLE player_character_skill_proficiencies
    ADD CONSTRAINT fk6hie856k99p1tdu2aalbxw376 FOREIGN KEY (player_character_id) REFERENCES character (id) ON DELETE NO ACTION;

ALTER TABLE session_note
    ADD CONSTRAINT fk6lbvnphvdwm6fcfdrf4lnj3g8 FOREIGN KEY (session_id) REFERENCES session (id) ON DELETE NO ACTION;

ALTER TABLE player_character_damage_resistances
    ADD CONSTRAINT fk97ply5jjimthjioeswylt2trb FOREIGN KEY (player_character_id) REFERENCES character (id) ON DELETE NO ACTION;

ALTER TABLE campaign_sections
    ADD CONSTRAINT fk9bceg8w1v9utc5t5c284vqae3 FOREIGN KEY (campaign_id) REFERENCES campaign (id) ON DELETE NO ACTION;

ALTER TABLE campaign_factions
    ADD CONSTRAINT fk_campaign_factions_faction FOREIGN KEY (faction_id) REFERENCES faction (id) ON DELETE NO ACTION;

ALTER TABLE campaign_tags
    ADD CONSTRAINT fk_campaign_tags_campaign FOREIGN KEY (campaign_id) REFERENCES campaign (id) ON DELETE NO ACTION;

ALTER TABLE campaign_tags
    ADD CONSTRAINT fk_campaign_tags_tag FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE NO ACTION;

ALTER TABLE combatant_actions
    ADD CONSTRAINT fk_combatant_actions FOREIGN KEY (combatant_id) REFERENCES combatant (id) ON DELETE CASCADE;

ALTER TABLE combatant
    ADD CONSTRAINT fk_combatant_encounter FOREIGN KEY (encounter_id) REFERENCES encounter (id) ON DELETE CASCADE;

ALTER TABLE combatant_special_abilities
    ADD CONSTRAINT fk_combatant_special_abilities FOREIGN KEY (combatant_id) REFERENCES combatant (id) ON DELETE CASCADE;

ALTER TABLE encounter
    ADD CONSTRAINT fk_encounter_session FOREIGN KEY (session_id) REFERENCES session (id) ON DELETE CASCADE;

ALTER TABLE character_log_magic_items
    ADD CONSTRAINT fk_player_log FOREIGN KEY (character_log_id) REFERENCES player_log (id) ON DELETE CASCADE;

ALTER TABLE player_log
    ADD CONSTRAINT fk_player_log_campaign FOREIGN KEY (campaign_id) REFERENCES campaign (id) ON DELETE NO ACTION;

ALTER TABLE prep_item
    ADD CONSTRAINT fk_prep_item_campaign FOREIGN KEY (campaign_id) REFERENCES campaign (id) ON DELETE CASCADE;

ALTER TABLE prep_item
    ADD CONSTRAINT fk_prep_item_session FOREIGN KEY (session_id) REFERENCES session (id) ON DELETE CASCADE;

ALTER TABLE quest
    ADD CONSTRAINT fk_quest_campaign FOREIGN KEY (campaign_id) REFERENCES campaign (id) ON DELETE CASCADE;

ALTER TABLE quest
    ADD CONSTRAINT fk_quest_session FOREIGN KEY (linked_session_id) REFERENCES session (id) ON DELETE SET NULL;

ALTER TABLE quest_tags
    ADD CONSTRAINT fk_quest_tags FOREIGN KEY (quest_id) REFERENCES quest (id) ON DELETE CASCADE;

ALTER TABLE character
    ADD CONSTRAINT fkba941srjut8hkfg8xmhw2q370 FOREIGN KEY (campaign_id) REFERENCES campaign (id) ON DELETE NO ACTION;

ALTER TABLE session
    ADD CONSTRAINT fkbinja8cuv5drp1qq434we9upg FOREIGN KEY (character_id) REFERENCES character (id) ON DELETE NO ACTION;

ALTER TABLE session_agenda_item
    ADD CONSTRAINT fkbo0l1nvjh1sj50t6nirrhxkdl FOREIGN KEY (session_id) REFERENCES session (id) ON DELETE NO ACTION;

ALTER TABLE session_decision
    ADD CONSTRAINT fkdx85xfkn2ar81gy5h1h907yx1 FOREIGN KEY (session_id) REFERENCES session (id) ON DELETE NO ACTION;

ALTER TABLE player_log_magic_items
    ADD CONSTRAINT fkf3mw30k5an8b14nn7jae0jvgf FOREIGN KEY (player_log_id) REFERENCES character_log (id) ON DELETE NO ACTION;

ALTER TABLE player_log_magic_items
    ADD CONSTRAINT fkf3mw30k5an8b14nn7jae0jvgf FOREIGN KEY (player_log_id) REFERENCES character_log (id) ON DELETE NO ACTION;

ALTER TABLE session_key_item
    ADD CONSTRAINT fkfghl7em5j9nmhgsaxclu54nll FOREIGN KEY (session_id) REFERENCES session (id) ON DELETE NO ACTION;

ALTER TABLE session
    ADD CONSTRAINT fkgpt5r2f8ocxgvmff1ppo9e3r2 FOREIGN KEY (campaign_id) REFERENCES campaign (id) ON DELETE NO ACTION;

ALTER TABLE session
    ADD CONSTRAINT fkkdljey5ke2noy9by2b3ov50rw FOREIGN KEY (player_character_id) REFERENCES character (id) ON DELETE NO ACTION;

ALTER TABLE player_character_damage_vulnerabilities
    ADD CONSTRAINT fkkw0key5hte4ucmmtid8a8im1s FOREIGN KEY (player_character_id) REFERENCES character (id) ON DELETE NO ACTION;

ALTER TABLE player_character_damage_immunities
    ADD CONSTRAINT fkmj60lviv61ilr1tbr13ajrxle FOREIGN KEY (player_character_id) REFERENCES character (id) ON DELETE NO ACTION;

ALTER TABLE character_log
    ADD CONSTRAINT fkpk20gbmji6e3h2m2ek8w7vigk FOREIGN KEY (campaign_id) REFERENCES campaign (id) ON DELETE NO ACTION;

ALTER TABLE player_character_inventory
    ADD CONSTRAINT fkq3yg2e5u3hpskv4930dh5lq3d FOREIGN KEY (character_id) REFERENCES character (id) ON DELETE NO ACTION;

ALTER TABLE session_encounter
    ADD CONSTRAINT fkt36v9kax6399goxnqyyhdic81 FOREIGN KEY (session_id) REFERENCES session (id) ON DELETE NO ACTION;

ALTER TABLE character_log
    ADD CONSTRAINT fktloh79091xomria49fbx7ii1v FOREIGN KEY (session_id) REFERENCES session (id) ON DELETE NO ACTION;

ALTER TABLE key_item_tracker
    ADD CONSTRAINT key_item_tracker_session_id_fkey FOREIGN KEY (session_id) REFERENCES session (id) ON DELETE CASCADE;

ALTER TABLE player_log_magic_items
    ADD CONSTRAINT player_log_magic_items_player_log_id_fkey FOREIGN KEY (player_log_id) REFERENCES player_log (id) ON DELETE CASCADE;