CREATE TABLE campaign_factions
(
    campaign_id BIGINT NOT NULL,
    faction_id  BIGINT NOT NULL,
    CONSTRAINT pk_campaign_factions PRIMARY KEY (campaign_id, faction_id)
);

CREATE TABLE campaign_location
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    campaign_id BIGINT,
    CONSTRAINT pk_campaignlocation PRIMARY KEY (id)
);

CREATE TABLE faction
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_faction PRIMARY KEY (id)
);

CREATE TABLE tag
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_tag PRIMARY KEY (id)
);

ALTER TABLE campaign
    ADD adventure_code VARCHAR(255);

ALTER TABLE campaign
    ADD max_level INTEGER;

ALTER TABLE campaign
    ADD min_level INTEGER;

ALTER TABLE campaign
    ADD status VARCHAR(255);

ALTER TABLE campaign
    ADD visible_to_players BOOLEAN;

ALTER TABLE campaign
    ALTER COLUMN max_level SET NOT NULL;

ALTER TABLE campaign
    ALTER COLUMN min_level SET NOT NULL;

ALTER TABLE campaign_tags
    ADD tag_id BIGINT;

ALTER TABLE campaign
    ALTER COLUMN visible_to_players SET NOT NULL;

ALTER TABLE campaign_tags
    ADD CONSTRAINT pk_campaign_tags PRIMARY KEY (campaign_id, tag_id);

ALTER TABLE faction
    ADD CONSTRAINT uc_faction_name UNIQUE (name);

ALTER TABLE tag
    ADD CONSTRAINT uc_tag_name UNIQUE (name);

ALTER TABLE campaign_location
    ADD CONSTRAINT FK_CAMPAIGNLOCATION_ON_CAMPAIGN FOREIGN KEY (campaign_id) REFERENCES campaign (id);

ALTER TABLE campaign_factions
    ADD CONSTRAINT fk_camfac_on_campaign FOREIGN KEY (campaign_id) REFERENCES campaign (id);

ALTER TABLE campaign_factions
    ADD CONSTRAINT fk_camfac_on_faction FOREIGN KEY (faction_id) REFERENCES faction (id);

ALTER TABLE campaign_tags
    ADD CONSTRAINT fk_camtag_on_tag FOREIGN KEY (tag_id) REFERENCES tag (id);

ALTER TABLE campaign_tags
DROP
COLUMN tags;

ALTER TABLE campaign
DROP
COLUMN thumbnail_url;

ALTER TABLE campaign
ALTER
COLUMN description TYPE VARCHAR(1000) USING (description::VARCHAR(1000));

ALTER TABLE campaign
    ALTER COLUMN title SET NOT NULL;