-- V4__fix_schema_issues.sql

-- 1. Fix campaign table columns
ALTER TABLE campaign
    ALTER COLUMN visible_to_players SET NOT NULL,
    ALTER COLUMN archived SET DEFAULT FALSE;

-- 2. Add auto-increment to IDs (PostgreSQL syntax)
ALTER TABLE campaign
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE prep_item
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE campaign_location
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- 3. Fix campaign_factions table

ALTER TABLE campaign_factions
    ADD CONSTRAINT fk_campaign_factions_faction
        FOREIGN KEY (faction_id) REFERENCES faction(id);

-- 4. Recreate campaign_tags table
DROP TABLE IF EXISTS campaign_tags;

CREATE TABLE campaign_tags (
                               campaign_id BIGINT NOT NULL,
                               tag_id BIGINT NOT NULL,
                               CONSTRAINT fk_campaign_tags_campaign
                                   FOREIGN KEY (campaign_id) REFERENCES campaign(id),
                               CONSTRAINT fk_campaign_tags_tag
                                   FOREIGN KEY (tag_id) REFERENCES tag(id)
);

-- 5. Fix session_agenda_item typo
ALTER TABLE session_agenda_item
    RENAME COLUMN sort_oder TO sort_order;

-- 6. Fix session table column
ALTER TABLE session
    RENAME COLUMN session_date TO session_date;

-- 7. Add missing foreign keys
ALTER TABLE campaign_location
    ADD CONSTRAINT fk_campaign_location_campaign
        FOREIGN KEY (campaign_id) REFERENCES campaign(id);

ALTER TABLE player_log
    ADD CONSTRAINT fk_player_log_campaign
        FOREIGN KEY (campaign_id) REFERENCES campaign(id);

-- 8. Add NOT NULL constraints
ALTER TABLE prep_item
    ALTER COLUMN campaign_id SET NOT NULL,
    ALTER COLUMN title SET NOT NULL;

-- 9. Fix session_encounter column

-- 10. Add default values
ALTER TABLE campaign
    ALTER COLUMN pinned SET DEFAULT FALSE,
    ALTER COLUMN version SET DEFAULT 0;