-- V4__fix_identity_columns.sql

-- 1. For tables already using SERIAL/BIGSERIAL (implicit sequence):
--    Drop the old sequence-based default and convert to IDENTITY
DO $$
    DECLARE
        tbl_name text;
    BEGIN
        FOR tbl_name IN VALUES ('campaign'), ('prep_item'), ('campaign_location')
            LOOP
                EXECUTE format('ALTER TABLE %I ALTER COLUMN id DROP IDENTITY IF EXISTS', tbl_name);
                EXECUTE format('DROP SEQUENCE IF EXISTS %I_seq CASCADE', tbl_name);
                EXECUTE format('ALTER TABLE %I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', tbl_name);
            END LOOP;
    END $$;


-- 2. Fix remaining schema issues
ALTER TABLE campaign
    RENAME COLUMN last_session_dat TO last_session_date;

ALTER TABLE campaign
    RENAME COLUMN visible_to_player TO visible_to_players;

ALTER TABLE session
    RENAME COLUMN session_dat TO session_date;

ALTER TABLE campaign ALTER COLUMN id DROP IDENTITY IF EXISTS;

ALTER TABLE campaign ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT * FROM campaign WHERE id = 1;

ALTER TABLE campaign ALTER COLUMN id RESTART WITH 1;
