#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/dm_campaigns_1234
#    username: postgres
#    password: admin123
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#
#  sql:
#    init:
#      mode: always
#
#  flyway:
#    enabled: true
#    locations: classpath:db/migration
#
#
#springdoc:
#  api-docs:
#    enabled: true
#  swagger-ui:
#    enabled: true
#    # Do NOT customize path here unless needed!
#    # Use default: http://localhost:8080/swagger-ui/index.html
#

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:admin123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

